---
- name: Alertmanager to EDA to AWX
  hosts: all

  sources:
    - name: Receive Alertmanager events
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:

    - name: Diagnose and remediate Linux high CPU
      condition: >
        event.alert.status == "firing" and
        event.alert.labels.alertname == "EDALabHighCPU"

      actions:

        - run_job_template:
            name: "Linux High CPU Diagnostic"
            organization: "Default"
            include_events: true
            job_args:
              limit: "{{ event.alert.labels.target_inventory_host }}"

        - run_job_template:
            name: "Linux High CPU Remediation"
            organization: "Default"
            include_events: true
            job_args:
              limit: "{{ event.alert.labels.target_inventory_host }}"

    - name: Existing synthetic EDA test
      condition: >
        event.alert.status == "firing" and
        event.alert.labels.alertname == "EDALabAlertmanagerTest"

      action:
        run_job_template:
          name: "EDA Test Job"
          organization: "Default"
          include_events: true
